name: Publish to OCI Registry

on:
  push:
    branches:
      - main

jobs:
  push-to-oci:
    runs-on: ubuntu-22.04-arm

    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      
      - name: Login no OCI Registry
        run: echo "${{ secrets.OCI_PASSWORD }}" | docker login ocir.sa-saopaulo-1.oci.oraclecloud.com/grfpdjlscx8c -u "${{ secrets.OCI_USERNAME }}" --password-stdin
      
      - name: Construir e publicar imagem
        run: |
          IMAGE_NAME=ocir.sa-saopaulo-1.oci.oraclecloud.com/grfpdjlscx8c/fission-function:latest
          docker build -t $IMAGE_NAME ./app
          docker push $IMAGE_NAME
